# Generated by Django 4.2.6 on 2023-10-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discos',
            name='ano',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discos',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
