# Generated by Django 4.2.6 on 2023-10-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_selofonografico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discos',
            name='selo_fonografico',
        ),
    ]
