# Generated by Django 4.2.6 on 2023-10-11 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_discos_selo_fonografico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selofonografico',
            name='disco',
        ),
        migrations.AddField(
            model_name='discos',
            name='selo_fonografico',
            field=models.ForeignKey(default= 1 , on_delete=django.db.models.deletion.CASCADE, to='core.selofonografico'),
            preserve_default=False,
        ),
    ]
