# Generated by Django 4.2.6 on 2023-10-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_selofonografico_disco_discos_selo_fonografico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='discos',
            name='artista',
            field=models.ManyToManyField(to='core.artista'),
        ),
    ]
