# Generated by Django 4.2.7 on 2023-11-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email_aluno',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_aluno',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome_cidade',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='sigla_estado',
            field=models.CharField(max_length=2, verbose_name='Sigla do Estado'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(max_length=100, verbose_name='Nome do curso'),
        ),
    ]
