# Generated by Django 4.2.7 on 2023-11-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='data_nacimento',
            new_name='data_nascimento',
        ),
    ]
